"""gallery_table

Revision ID: 06a2f51cf00e
Revises: 
Create Date: 2021-11-22 11:24:38.155963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a2f51cf00e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery',
    sa.Column('img_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('img_name', sa.String(), nullable=True),
    sa.Column('img_tags', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('img_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gallery')
    # ### end Alembic commands ###
